services:
  # 1. Database MongoDB
  mongo_db:
    image: mongo:latest
    restart: always
    container_name: utc_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - utc_network
    mem_limit: 512m
    cpus: 0.50
    # --- LIMITASI RESOURCE (Docker Swarm) ---
    deploy:
      resources:
        limits:
          cpus: '0.50'        # Maksimal pakai 50% dari 1 Core CPU
          memory: 512M        # Maksimal RAM fisik 512MB (Selebihnya masuk Swap)
        reservations:
          memory: 128M        # Garansi RAM minimal 128MB agar stabil
          

  # 2. Backend (Server API)
  backend:
    build: ./backend
    container_name: utc_backend
    restart: always
    ports:
      - "5200:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo_db:27017/bengkel_utc
      - JWT_SECRET=${JWT_SECRET:-change_this_in_production}
      - NODE_ENV=production
      - WAHA_URL=http://waha:8000
      - WAHA_API_KEY=adminutc28
      - IS_CAMPUS_EVENT=false
    depends_on:
      - mongo_db
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - utc_network
    mem_limit: 300m
    cpus: 0.50
    # --- LIMITASI RESOURCE (Docker Swarm) ---
    deploy:
      resources:
        limits:
          cpus: '0.50'        # Maksimal pakai 50% dari 1 Core CPU
          memory: 300M        # Node.js backend cukup ringan, 300MB cukup
        reservations:
          memory: 100M        # Garansi RAM minimal

  # 3. Frontend (Web Interface)
  frontend:
    build: ./frontend
    container_name: utc_frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - utc_network
    mem_limit: 128m
    cpus: 0.5
    # --- LIMITASI RESOURCE (Docker Swarm) ---
    deploy:
      resources:
        limits:
          cpus: '0.50'        # Frontend statis (Nginx) sangat ringan, 50% CPU cukup
          memory: 128M        # 128MB sangat cukup untuk serve file statis
        reservations:
          memory: 32M

  # 4. WAHA (WhatsApp HTTP API)
  waha:
    image: devlikeapro/waha:latest
    container_name: utc_waha
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - WAHA_WHATSAPP_DEFAULT_SESSION=default
      - WAHA_PRINT_QR=true
      - WAHA_API_KEY=adminutc28
      - WHATSAPP_SWAGGER_USERNAME=admin-utc01
      - WHATSAPP_SWAGGER_PASSWORD=adminutc28
      - WAHA_DASHBOARD_USERNAME=admin-utc01
      - WAHA_DASHBOARD_PASSWORD=adminutc28
      - WAHA_WHATSAPP_READ_MESSAGES=true
      - WAHA_WHATSAPP_SEND_MESSAGES=true
      - WAHA_WHATSAPP_READ_CONTACTS=true
    networks:
      - utc_network
    mem_limit: 1512m
    cpus: 1.5

networks:
  utc_network:
    driver: bridge

volumes:
  mongo_data: {}